#!/usr/bin/env bash
# installs nginx web server and configures a custom 404 page

# Update the package manager's package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create the 404.html file with the desired content
sudo bash -c 'echo "Ceci n est pas une page" > /var/www/html/404.html'

# Modify the server block in the default nginx configuration file
sudo sed -i 's#root /var/www/html;#root /var/www/html;\nerror_page 404 /404.html;\n  location /404.html {\n    root /var/www/html;\n  }#' /etc/nginx/sites-available/default

# Test the configuration file for syntax errors
sudo nginx -t

# Reload the nginx service to apply the changes
sudo service nginx reload
